function HowItWorks() {
    return (
        <div className="flex flex-col gap-8 max-w-2xl mx-auto">
            <h1 className="text-4xl font-bold text-gray-600 text-center">How It Works</h1>

            {/* Privacy */}
            <div className="bg-green-50 rounded-2xl p-6 border border-green-200">
                <h2 className="text-xl font-bold text-green-700 mb-2">🔒 Your Privacy</h2>
                <p className="text-green-700 leading-relaxed">
                    We do not store any of your photos — all image processing
                    happens <strong>locally in your browser</strong>. Only the extracted
                    skin tone hex values (e.g. #c4956a) are sent to the AI for color
                    suggestions. Your images never leave your device.
                </p>
            </div>

            {/* Steps */}
            <div className="bg-white rounded-2xl p-6 shadow-sm border border-gray-100">
                <h2 className="text-xl font-bold text-gray-600 mb-4">The Process</h2>
                <ol className="flex flex-col gap-3 list-decimal pl-5 text-gray-500 leading-relaxed">
                    <li>
                        <strong>Upload or capture</strong> a photo using your
                        device's file picker or camera.
                    </li>
                    <li>
                        We <strong>compress</strong> the image locally to optimize processing.
                    </li>
                    <li>
                        Using the face-api.js library, we detect your <strong>full face</strong> using
                        68-point facial landmarks (forehead, eyebrows, jaw, cheeks, nose, mouth).
                    </li>
                    <li>
                        We extract pixel color data from the detected face area,
                        filtering out shadows and highlights.
                    </li>
                    <li>
                        <strong>K-Means++ clustering</strong> finds 5 dominant hex values
                        representing your skin tones.
                    </li>
                    <li>
                        These hex values (not your photo) are sent to an AI model
                        which generates <strong>seasonal color recommendations</strong> based
                        on color theory (spring, summer, fall, winter) plus a jewelry suggestion.
                    </li>
                    <li>
                        Results are displayed with clickable, copyable color swatches.
                        You can <strong>save palettes locally</strong> or <strong>export as PNG</strong>.
                    </li>
                </ol>
            </div>

            {/* Saved data */}
            <div className="bg-white rounded-2xl p-6 shadow-sm border border-gray-100">
                <h2 className="text-xl font-bold text-gray-600 mb-2">💾 Saved Palettes</h2>
                <p className="text-gray-500 leading-relaxed">
                    Saved palettes are stored in your browser's local storage — no account needed.
                    You can view, export, or delete them from the{' '}
                    <strong>"my palettes"</strong> page. Clearing your browser data will remove them.
                </p>
            </div>

            {/* Disclaimer */}
            <div className="bg-amber-50 rounded-2xl p-6 border border-amber-200">
                <h2 className="text-xl font-bold text-amber-700 mb-2">⚠️ Disclaimer</h2>
                <p className="text-amber-700 leading-relaxed">
                    Color recommendations are generated by an AI model and may vary
                    between sessions. While we aim to provide helpful suggestions based
                    on color theory, results are meant as inspiration — personal preference
                    always comes first!
                </p>
            </div>
        </div>
    );
}

export default HowItWorks;
